--------------------------------------------------------
--  Arquivo criado - Segunda-feira-Maio-22-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table EMAIL
--------------------------------------------------------

  CREATE TABLE "GABRIEL"."EMAIL" 
   (	"EMA_CODIGO" NUMBER(4,0), 
	"EMA_EMAIL" VARCHAR2(30 BYTE), 
	"EMA_SENHA" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into GABRIEL.EMAIL
SET DEFINE OFF;
Insert into GABRIEL.EMAIL (EMA_CODIGO,EMA_EMAIL,EMA_SENHA) values ('1','gabriel.texteis@gmail.com','gabriel');
Insert into GABRIEL.EMAIL (EMA_CODIGO,EMA_EMAIL,EMA_SENHA) values ('3','diegoalmeida@hotmail.com','diego');
Insert into GABRIEL.EMAIL (EMA_CODIGO,EMA_EMAIL,EMA_SENHA) values ('4','ericaalmeida@hotmail.com','erica');
Insert into GABRIEL.EMAIL (EMA_CODIGO,EMA_EMAIL,EMA_SENHA) values ('5','Maria José de Almeida','maria');
Insert into GABRIEL.EMAIL (EMA_CODIGO,EMA_EMAIL,EMA_SENHA) values ('6','dsadsa','asd');
--------------------------------------------------------
--  DDL for Index SYS_C007133
--------------------------------------------------------

  CREATE UNIQUE INDEX "GABRIEL"."SYS_C007133" ON "GABRIEL"."EMAIL" ("EMA_CODIGO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table EMAIL
--------------------------------------------------------

  ALTER TABLE "GABRIEL"."EMAIL" ADD PRIMARY KEY ("EMA_CODIGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "GABRIEL"."EMAIL" MODIFY ("EMA_SENHA" NOT NULL ENABLE);
  ALTER TABLE "GABRIEL"."EMAIL" MODIFY ("EMA_EMAIL" NOT NULL ENABLE);
  ALTER TABLE "GABRIEL"."EMAIL" MODIFY ("EMA_CODIGO" NOT NULL ENABLE);
