--------------------------------------------------------
--  Arquivo criado - Segunda-feira-Maio-22-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table USUARIO
--------------------------------------------------------

  CREATE TABLE "GABRIEL"."USUARIO" 
   (	"USU_CODIGO" NUMBER(4,0), 
	"EMA_CODIGO1" NUMBER(4,0), 
	"USU_NOME" VARCHAR2(30 BYTE), 
	"USU_SEXO" VARCHAR2(2 BYTE), 
	"USU_IDADE" NUMBER(8,0), 
	"USU_CARGO" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EMAIL
--------------------------------------------------------

  CREATE TABLE "GABRIEL"."EMAIL" 
   (	"EMA_CODIGO" NUMBER(4,0), 
	"EMA_EMAIL" VARCHAR2(30 BYTE), 
	"EMA_SENHA" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into GABRIEL.USUARIO
SET DEFINE OFF;
Insert into GABRIEL.USUARIO (USU_CODIGO,EMA_CODIGO1,USU_NOME,USU_SEXO,USU_IDADE,USU_CARGO) values ('1','1','Gabriel de Almeida Batista','M','19','Gerente');
Insert into GABRIEL.USUARIO (USU_CODIGO,EMA_CODIGO1,USU_NOME,USU_SEXO,USU_IDADE,USU_CARGO) values ('3','3','Érica de Almeida Batista','F','21','Programador');
Insert into GABRIEL.USUARIO (USU_CODIGO,EMA_CODIGO1,USU_NOME,USU_SEXO,USU_IDADE,USU_CARGO) values ('4','4','mariajalmeida@hotmail.com','F','22','Gerente');
Insert into GABRIEL.USUARIO (USU_CODIGO,EMA_CODIGO1,USU_NOME,USU_SEXO,USU_IDADE,USU_CARGO) values ('5','5','dsadsa','F','26','Analista');
--------------------------------------------------------
--  DDL for Index SYS_C007158
--------------------------------------------------------

  CREATE UNIQUE INDEX "GABRIEL"."SYS_C007158" ON "GABRIEL"."USUARIO" ("USU_CODIGO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table USUARIO
--------------------------------------------------------

  ALTER TABLE "GABRIEL"."USUARIO" ADD PRIMARY KEY ("USU_CODIGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "GABRIEL"."USUARIO" MODIFY ("USU_CARGO" NOT NULL ENABLE);
  ALTER TABLE "GABRIEL"."USUARIO" MODIFY ("USU_IDADE" NOT NULL ENABLE);
  ALTER TABLE "GABRIEL"."USUARIO" MODIFY ("USU_SEXO" NOT NULL ENABLE);
  ALTER TABLE "GABRIEL"."USUARIO" MODIFY ("USU_NOME" NOT NULL ENABLE);
  ALTER TABLE "GABRIEL"."USUARIO" MODIFY ("EMA_CODIGO1" NOT NULL ENABLE);
  ALTER TABLE "GABRIEL"."USUARIO" MODIFY ("USU_CODIGO" NOT NULL ENABLE);
